apiVersion: v1
kind: Service
metadata:
  name: productivity-calculator-service
spec:
  type: LoadBalancer
  selector:
    app: productivity-calculator
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
