name: Deploy Productivity Calculator App with MySQL

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        pip3 install mysql-connector-python

    - name: Setup MySQL
      run: |
        sudo apt-get install mysql-server
        sudo mysql -e "CREATE DATABASE productivity_app;"
        sudo mysql -e "CREATE USER 'app_user'@'localhost' IDENTIFIED BY 'password';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON productivity_app.* TO 'app_user'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /path/to/your/project
          git pull origin main  # Change 'main' if your default branch is different
          pip3 install mysql-connector-python
          python3 app.py  # Replace 'your_script_name.py' with the name of your Python script containing the provided code
