version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Gordito10?
    ports:
      - "3306:3306"
  python-app:
    build: .
    depends_on:
      - mysql