version: '3.8'

services:
  app:
    build: .
    environment:
      - HOST=192.168.68.51
      - PORT=3306
      - USER=ula
      - PASSWORD=Gordito10
      - DATABASE=ProductivityCalculator
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"