version: '3.8'

services:
  app:
    build: .
    environment:
      - HOST=localhost
      - PORT=3306
      - USER=root
      - PASSWORD=gordito
      - DATABASE=ProductivityCalculator
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"