version: '3.8'

services:
  app:
    build: .
    environment:
      - HOST=mysql
      - PORT=3307
      - USER=ula
      - PASSWORD=Gordito10?
      - DATABASE=ProductivityCalculator
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: gordito
      MYSQL_DATABASE: ProductivityCalculator
    ports:
      - "3307:3306"
    networks:
      - mynetwork

networks:
  mynetwork: