apiVersion: apps/v1
kind: Deployment
metadata:
  name: productivity-calculator-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productivity-calculator
  template:
    metadata:
      labels:
        app: productivity-calculator
    spec:
      containers:
      - name: productivity-calculator
        image: urszulach/python-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
‹