apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: productivity-calculator-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productivity-calculator-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
