version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      HOST: db
      USER: root
      PASSWORD: gordito
      DATABASE: ProductivityCalculator
      PORT: 3307
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: gordito
      MYSQL_DATABASE: ProductivityCalculator
    ports:
      - "3307:3306"