pipeline {
    agent any

    triggers {
        pollSCM('H/5 * * * *') // Polls the SCM every 5 minutes
    }

    environment {
        DOCKER_IMAGE = 'urszulach/python-app'
        DOCKER_REGISTRY = 'docker.io'
        K8S_DEPLOYMENT = 'productivity-calculator-deployment'
        K8S_NAMESPACE = 'default'
        AWS_REGION = 'eu-west-2' // For Terraform
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        // Terraform Stages Begin
        stage('Terraform Init') {
            steps {
                dir('infra') {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir('infra') {
                    sh 'terraform plan -var-file="../terraform/dev.tfvars" -out="../tfplan/dev.tfplan"'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    def userApproval = input message: 'Apply the Terraform changes?', ok: 'Apply'
                    if (userApproval) {
                        dir('infra') {
                            sh 'terraform apply "../tfplan/dev.tfplan"'
                        }
                    }
                }
            }
        }
        // Terraform Stages End

        stage('Install Dependencies') {
            steps {
                sh '''
                    sudo apt-get update
                    sudo apt-get install -y python3 python3-venv python3-pip mysql-server
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip --break-system-packages
                    pip install -r requirements.txt mysql-connector-python --break-system-packages
                '''
            }
        }

        stage('Build Artifact') {
            steps {
                sh '''
                python setup.py sdist bdist_wheel
                ls dist/
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t ${DOCKER_IMAGE} .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-credentials', passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login ${DOCKER_REGISTRY} -u "$DOCKER_USERNAME" --password-stdin
                        docker push ${DOCKER_IMAGE}
                    '''
                }
            }
        }

        stage('Rolling Update') {
            steps {
                script {
                    sh 'kubectl rollout status deployment/productivity-calculator-deployment'
                }
            }
        }        

        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig-credentials', variable: 'KUBECONFIG_FILE')]) {
                    sh '''
                        export KUBECONFIG=$KUBECONFIG_FILE
                        kubectl set image deployment/${K8S_DEPLOYMENT} ${K8S_DEPLOYMENT}=${DOCKER_IMAGE} --namespace=${K8S_NAMESPACE}
                        kubectl rollout status deployment/${K8S_DEPLOYMENT} --namespace=${K8S_NAMESPACE}
                    '''
                }
            }
        }

        stage('Monitor Logs') {
            steps {
                script {
                    sh '''
                        kubectl logs -f deployment/${K8S_DEPLOYMENT} --namespace=${K8S_NAMESPACE}
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'Build succeeded!'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
